/**
 * Agent 面板状态管理组合式函数
 * 管理 Agent 对话列表、创建、删除等操作
 */
import { ref, computed, unref, watch } from 'vue'
import { getSessionImChannel } from '@shared/external-im-meta'

const PINNED_PROJECTS_STORAGE_KEY = 'agent.leftPanel.pinnedProjectKeys'
const EXPANDED_PROJECTS_STORAGE_KEY = 'agent.leftPanel.expandedProjectKeys'
const PROJECT_ORDER_STORAGE_KEY = 'agent.leftPanel.projectOrderKeys'
const UNCATEGORIZED_PROJECT_KEY = 'uncategorized'
const EXTERNAL_IM_GROUP_KEY = 'external-im'

// 模块级别的已关闭会话集合（跨组件共享）
// 用于在队列自动消费前检查会话是否已关闭
const closedSessionIds = new Set()

/**
 * 检查会话是否已关闭
 * @param {string} sessionId
 * @returns {boolean}
 */
export function isSessionClosed(sessionId) {
  return closedSessionIds.has(sessionId)
}

/**
 * 标记会话为已关闭（供内部使用）
 * @param {string} sessionId
 */
function markSessionClosed(sessionId) {
  closedSessionIds.add(sessionId)
  console.log('[useAgentPanel] 🚫 Marked session as closed:', sessionId)
}

/**
 * 移除会话的关闭标记（供重新打开使用）
 * @param {string} sessionId
 */
export function unmarkSessionClosed(sessionId) {
  closedSessionIds.delete(sessionId)
  console.log('[useAgentPanel] ✅ Unmarked session as closed:', sessionId)
}

function isEmbeddedAppConversation(conv) {
  if (conv?.sessionAppId) {
    return false
  }

  const ownerClientId = typeof conv?.ownerClientId === 'string' ? conv.ownerClientId : ''
  const clientType = typeof conv?.clientType === 'string' ? conv.clientType : ''

  return ownerClientId.startsWith('embed:') ||
    clientType === 'embedded' ||
    conv?.projectKind === 'embedded'
}

function isChatConversation(conv) {
  return typeof conv?.type !== 'string' || conv.type === 'chat'
}

function isListableConversation(conv) {
  return isChatConversation(conv) && !isEmbeddedAppConversation(conv)
}

function isAutoGeneratedImConversation(conv) {
  // `imChannel` is cleared when a target is unbound, while `source` retains
  // the session's IM-origin provenance for grouping historical auto sessions.
  if (!isImOriginConversation(conv)) return false
  return conv?.projectKind === 'agent-output' ||
    conv?.cwdAuto === true ||
    !normalizeProjectId(conv?.projectId)
}

function isImOriginConversation(conv) {
  return Boolean(getSessionImChannel(conv)) || conv?.source === 'im-inbound'
}

function matchesSourceFilter(conv, selectedSource) {
  if (selectedSource === 'all') return true

  const imChannel = getSessionImChannel(conv)
  if (selectedSource === 'no-im') return !isImOriginConversation(conv)
  return imChannel === selectedSource
}

function matchesTaskFilter(conv, selectedTaskFilter) {
  if (selectedTaskFilter === 'all') return true

  const hasTask = Boolean(conv?.taskId)
  return selectedTaskFilter === 'with-task' ? hasTask : !hasTask
}

function matchesAppFilter(conv, selectedAppFilter) {
  if (selectedAppFilter === 'all') return true
  if (selectedAppFilter === 'session-app') return Boolean(conv?.sessionAppId)
  if (selectedAppFilter === 'plain-session') return !conv?.sessionAppId
  return conv?.sessionAppId === selectedAppFilter
}

function normalizeCwd(cwd) {
  return typeof cwd === 'string' ? cwd.trim() : ''
}

function normalizeProjectId(projectId) {
  if (projectId === null || projectId === undefined || projectId === '') return ''
  return String(projectId)
}

function getConversationDirectoryKey(conv) {
  const projectId = normalizeProjectId(conv?.projectId)
  if (projectId) return `project:${projectId}`
  return ''
}

function getFallbackDirectoryEntry() {
  return {
    key: UNCATEGORIZED_PROJECT_KEY,
    path: '',
    cwd: '',
    projectId: null,
    projectName: null,
    projectKind: 'uncategorized',
    isFallback: true,
    pathValid: false
  }
}

function getProjectTimestamp(project) {
  const value = project?.last_activity || project?.lastActivity || project?.last_opened_at || project?.lastOpenedAt || project?.updated_at || project?.updatedAt || project?.created_at || project?.createdAt
  if (typeof value === 'number') return value
  const timestamp = Date.parse(value || '')
  return Number.isFinite(timestamp) ? timestamp : 0
}

function getVisibleProjectEntries(projects) {
  const entries = []
  const seen = new Set()

  for (const project of Array.isArray(projects) ? projects : []) {
    const projectId = normalizeProjectId(project?.id)
    const projectKind = project?.project_kind || project?.projectKind || 'workspace'
    if (!projectId || seen.has(projectId) || projectKind !== 'workspace' || Number(project?.is_hidden) === 1) {
      continue
    }

    const path = normalizeCwd(project?.path || project?.projectPath)
    if (!path) continue

    seen.add(projectId)
    entries.push({
      key: `project:${projectId}`,
      path,
      // Keep the alias for existing presentation callers. It is derived from projects.path.
      cwd: path,
      projectId,
      projectName: project?.name || null,
      projectKind,
      pathValid: project?.pathValid !== false,
      latestTimestamp: getProjectTimestamp(project),
      isFallback: false
    })
  }

  return entries
}

function getLocalStorage() {
  try {
    return typeof window !== 'undefined' ? window.localStorage : null
  } catch {
    return null
  }
}

function uniqueStrings(values) {
  const seen = new Set()
  const result = []
  for (const value of values || []) {
    const normalized = typeof value === 'string' ? value.trim() : ''
    if (normalized && !seen.has(normalized)) {
      seen.add(normalized)
      result.push(normalized)
    }
  }
  return result
}

function normalizeLegacyProjectPath(path) {
  const normalized = normalizeCwd(path).replace(/\\/g, '/')
  if (!normalized) return ''

  const withoutTrailingSeparators = normalized.length > 1 && !/^[A-Za-z]:\/$/.test(normalized)
    ? normalized.replace(/\/+$/, '')
    : normalized

  return /^[A-Za-z]:\//.test(withoutTrailingSeparators)
    ? withoutTrailingSeparators.toLocaleLowerCase()
    : withoutTrailingSeparators
}

function migrateLegacyProjectPreferenceKeys(keys, projectEntries) {
  const projectKeyByPath = new Map()
  for (const entry of projectEntries || []) {
    const pathKey = normalizeLegacyProjectPath(entry?.path)
    if (pathKey && entry?.key) projectKeyByPath.set(pathKey, entry.key)
  }

  return uniqueStrings((Array.isArray(keys) ? keys : []).map(key => {
    if (!key.startsWith('cwd:')) return key
    return projectKeyByPath.get(normalizeLegacyProjectPath(key.slice('cwd:'.length))) || key
  }))
}

function sameStringList(left, right) {
  return left.length === right.length && left.every((value, index) => value === right[index])
}

function loadStringList(storageKey) {
  const storage = getLocalStorage()
  if (!storage) return { found: false, values: [] }

  try {
    const raw = storage.getItem(storageKey)
    if (raw === null || raw === undefined) return { found: false, values: [] }
    const parsed = JSON.parse(raw)
    return {
      found: true,
      values: Array.isArray(parsed) ? uniqueStrings(parsed) : []
    }
  } catch {
    return { found: false, values: [] }
  }
}

function saveStringList(storageKey, values) {
  const storage = getLocalStorage()
  if (!storage) return

  try {
    storage.setItem(storageKey, JSON.stringify(uniqueStrings(values)))
  } catch {
    // 本地 UI 状态不可写时，不影响会话列表本身。
  }
}

function getConversationTimestamp(conv) {
  const ts = Date.parse(conv?.updatedAt || conv?.createdAt || '')
  return Number.isFinite(ts) ? ts : 0
}

function getDirectorySortName(entry) {
  const name = entry?.projectName || entry?.path || entry?.key || ''
  return String(name).toLocaleLowerCase()
}

export function useAgentPanel({ projects: projectSource = null } = {}) {
  const conversations = ref([])
  const loading = ref(false)
  const selectedSource = ref('all')
  const selectedTaskFilter = ref('all')
  const selectedAppFilter = ref('all')
  const sessionApps = ref([])
  const pinnedProjectKeys = ref(loadStringList(PINNED_PROJECTS_STORAGE_KEY).values)
  const projectOrderKeys = ref(loadStringList(PROJECT_ORDER_STORAGE_KEY).values)
  const visibleProjectEntries = computed(() => getVisibleProjectEntries(unref(projectSource)))
  // 首次没有偏好时保持收起，由当前活跃会话所在项目按需展开。
  const expandedProjectKeys = ref(loadStringList(EXPANDED_PROJECTS_STORAGE_KEY).values)

  const migrateStoredProjectPreferenceKeys = () => {
    const projectEntries = visibleProjectEntries.value
    if (projectEntries.length === 0) return

    const migrate = (target, storageKey) => {
      const migrated = migrateLegacyProjectPreferenceKeys(target.value, projectEntries)
      if (sameStringList(migrated, target.value)) return
      target.value = migrated
      saveStringList(storageKey, migrated)
    }

    migrate(pinnedProjectKeys, PINNED_PROJECTS_STORAGE_KEY)
    migrate(expandedProjectKeys, EXPANDED_PROJECTS_STORAGE_KEY)
    migrate(projectOrderKeys, PROJECT_ORDER_STORAGE_KEY)
  }

  watch(visibleProjectEntries, migrateStoredProjectPreferenceKeys, { immediate: true })

  const isVisibleProjectConversation = (conv) => {
    const projectKey = getConversationDirectoryKey(conv)
    return Boolean(projectKey && visibleProjectEntries.value.some(entry => entry.key === projectKey))
  }

  // Auto-created IM sessions keep their dedicated bucket only while their
  // project identity is internal or unavailable. A visible project binding
  // takes precedence so every visible project-owned conversation stays in its tree.
  const isExternalImConversation = (conv) => {
    return isAutoGeneratedImConversation(conv) && !isVisibleProjectConversation(conv)
  }

  /**
   * 加载对话列表（后端已合并活跃+历史）
   */
  const loadConversations = async () => {
    if (!window.electronAPI) return

    loading.value = true
    try {
      const [list, apps] = await Promise.all([
        window.electronAPI.listAgentSessions(),
        window.electronAPI.listSessionApps?.()
      ])
      conversations.value = Array.isArray(list)
        ? list.filter(isListableConversation)
        : []
      sessionApps.value = Array.isArray(apps) ? apps : []
    } catch (err) {
      console.error('[useAgentPanel] loadConversations error:', err)
      conversations.value = []
      sessionApps.value = []
    } finally {
      loading.value = false
    }
  }

  /**
   * 创建新对话
   * @param {Object} options - { type, title, cwd, apiProfileId }
   * @returns {Object} 会话对象
   */
  const createConversation = async (options = {}) => {
    if (!window.electronAPI) return null

    try {
      const session = await window.electronAPI.createAgentSession({
        type: options.type || 'chat',
        title: options.title || '',
        projectId: options.projectId || null,
        cwd: options.cwd || null,
        apiProfileId: options.apiProfileId || null
      })

      if (session && !session.error) {
        conversations.value.unshift(session)
        ensureCreatedConversationVisible(session)
        return session
      } else {
        console.error('[useAgentPanel] create error:', session?.error)
        return null
      }
    } catch (err) {
      console.error('[useAgentPanel] createConversation error:', err)
      return null
    }
  }

  /**
   * 关闭对话（软关闭，标记为 closed）
   */
  const closeConversation = async (sessionId) => {
    if (!window.electronAPI) return

    // CRITICAL: 立即标记会话为已关闭，阻止队列自动消费
    markSessionClosed(sessionId)

    try {
      await window.electronAPI.closeAgentSession(sessionId)
      // 更新列表中的状态
      const conv = conversations.value.find(c => c.id === sessionId)
      if (conv) {
        conv.status = 'closed'
      }
    } catch (err) {
      console.error('[useAgentPanel] closeConversation error:', err)
    }
  }

  /**
   * 物理删除对话
   */
  const deleteConversation = async (sessionId) => {
    if (!window.electronAPI) return

    try {
      await window.electronAPI.deleteAgentConversation(sessionId)
      const index = conversations.value.findIndex(c => c.id === sessionId)
      if (index !== -1) {
        conversations.value.splice(index, 1)
      }

      // CRITICAL: 清理关闭标记，防止内存泄露
      closedSessionIds.delete(sessionId)
      console.log('[useAgentPanel] 🗑️ Removed closed mark for deleted session:', sessionId)
    } catch (err) {
      console.error('[useAgentPanel] deleteConversation error:', err)
    }
  }

  /**
   * 将指定会话上浮到列表最前（收到 agent:result 时调用）
   */
  const bumpConversation = (sessionId) => {
    const index = conversations.value.findIndex(c => c.id === sessionId)
    if (index > 0) {
      const [conv] = conversations.value.splice(index, 1)
      conv.updatedAt = new Date().toISOString()
      conversations.value.unshift(conv)
    } else if (index === 0) {
      conversations.value[0].updatedAt = new Date().toISOString()
    }
  }

  /**
   * 重命名对话
   */
  const renameConversation = async (sessionId, title) => {
    if (!window.electronAPI) return

    try {
      await window.electronAPI.renameAgentSession({ sessionId, title })
      const conv = conversations.value.find(c => c.id === sessionId)
      if (conv) {
        conv.title = title
      }
    } catch (err) {
      console.error('[useAgentPanel] renameConversation error:', err)
    }
  }

  // 当前选中的项目筛选 key（null = 全部；仅 project:<id>）
  const selectedCwd = ref(null)

  const sourceFilteredConversations = computed(() => {
    return conversations.value.filter(conv => matchesSourceFilter(conv, selectedSource.value))
  })

  const taskFilteredConversations = computed(() => {
    return sourceFilteredConversations.value.filter(conv => matchesTaskFilter(conv, selectedTaskFilter.value))
  })

  const appFilterOptions = computed(() => {
    const appMap = new Map()
    for (const app of sessionApps.value) {
      if (!app?.appId) continue
      appMap.set(app.appId, {
        id: app.appId,
        name: app.name || app.appId
      })
    }
    for (const conv of taskFilteredConversations.value) {
      if (!conv?.sessionAppId) continue
      if (!appMap.has(conv.sessionAppId)) {
        appMap.set(conv.sessionAppId, {
          id: conv.sessionAppId,
          name: conv.sessionAppId
        })
      }
    }

    return [
      { key: 'all', label: 'all' },
      { key: 'session-app', label: 'session-app' },
      { key: 'plain-session', label: 'plain-session' },
      ...Array.from(appMap.values()).map(app => ({
        key: app.id,
        label: app.name
      }))
    ]
  })

  watch(appFilterOptions, (options) => {
    if (!options.some(option => option.key === selectedAppFilter.value)) {
      selectedAppFilter.value = 'all'
    }
  }, { immediate: true })

  /**
   * 从当前候选对话中提取最近目录，并与手动打开目录合并，最多展示 10 个
   */
  const availableDirectories = computed(() => {
    return visibleProjectEntries.value
  })

  const selectCwd = (projectKey) => {
    const value = normalizeCwd(projectKey)
    if (!value) {
      selectedCwd.value = null
      return
    }

    if (value.startsWith('project:') && value.length > 'project:'.length) {
      selectedCwd.value = value
      return
    }

    selectedCwd.value = null
  }

  watch(availableDirectories, (nextDirectories) => {
    if (selectedCwd.value && !nextDirectories.some(directory => directory.key === selectedCwd.value)) {
      selectedCwd.value = null
    }
  }, { immediate: true })

  /**
   * 按 selectedCwd 过滤后的对话列表
   */
  const filteredConversations = computed(() => {
    return taskFilteredConversations.value.filter(conv => {
      if (!matchesAppFilter(conv, selectedAppFilter.value)) return false
      return !selectedCwd.value || getConversationDirectoryKey(conv) === selectedCwd.value
    })
  })

  const normalProjectConversations = computed(() => {
    return filteredConversations.value.filter(conv => !isExternalImConversation(conv))
  })

  const externalImConversations = computed(() => {
    return filteredConversations.value
      .filter(isExternalImConversation)
      .sort((a, b) => getConversationTimestamp(b) - getConversationTimestamp(a))
  })

  const externalImExpanded = computed(() => expandedProjectKeys.value.includes(EXTERNAL_IM_GROUP_KEY))

  const ensureCreatedConversationVisible = (session) => {
    if (!matchesSourceFilter(session, selectedSource.value)) {
      selectedSource.value = 'all'
    }
    if (!matchesTaskFilter(session, selectedTaskFilter.value)) {
      selectedTaskFilter.value = 'all'
    }
    if (!matchesAppFilter(session, selectedAppFilter.value)) {
      selectedAppFilter.value = 'all'
    }
    if (selectedCwd.value && getConversationDirectoryKey(session) !== selectedCwd.value) {
      selectedCwd.value = null
    }
  }

  const isProjectPinned = (projectKey) => pinnedProjectKeys.value.includes(projectKey)

  const buildProjectConversationGroups = (sourceConversations) => {
    const groupsByKey = new Map()

    const createGroup = (entry) => ({
      ...entry,
      items: [],
      count: 0,
      latestTimestamp: entry.latestTimestamp || 0,
      hasOpenConversation: false
    })

    // The project list owns the normal tree, including zero-session projects.
    for (const entry of visibleProjectEntries.value) {
      groupsByKey.set(entry.key, createGroup(entry))
    }

    for (const conv of sourceConversations) {
      const projectKey = getConversationDirectoryKey(conv)
      let group = groupsByKey.get(projectKey)
      if (!group) {
        if (!groupsByKey.has(UNCATEGORIZED_PROJECT_KEY)) {
          const fallback = getFallbackDirectoryEntry()
          groupsByKey.set(fallback.key, createGroup(fallback))
        }
        group = groupsByKey.get(UNCATEGORIZED_PROJECT_KEY)
      }

      const timestamp = getConversationTimestamp(conv)
      group.items.push(conv)
      group.count += 1
      group.latestTimestamp = Math.max(group.latestTimestamp, timestamp)
      group.hasOpenConversation ||= conv.status !== 'closed'
    }

    const pinnedOrder = new Map(pinnedProjectKeys.value.map((key, index) => [key, index]))
    const projectOrder = new Map(projectOrderKeys.value.map((key, index) => [key, index]))

    const groups = Array.from(groupsByKey.values())
      .map(group => ({
        ...group,
        items: group.items.sort((a, b) => getConversationTimestamp(b) - getConversationTimestamp(a)),
        pinned: !group.isFallback && pinnedOrder.has(group.key),
        expanded: expandedProjectKeys.value.includes(group.key)
      }))

    const fallbackGroups = groups.filter(group => group.isFallback)
    const projectGroups = groups
      .filter(group => !group.isFallback)
      .sort((a, b) => {
        if (a.pinned !== b.pinned) return a.pinned ? -1 : 1
        if (a.pinned) return pinnedOrder.get(a.key) - pinnedOrder.get(b.key)

        const aOrderIndex = projectOrder.get(a.key)
        const bOrderIndex = projectOrder.get(b.key)
        if (aOrderIndex !== undefined || bOrderIndex !== undefined) {
          if (aOrderIndex === undefined) return 1
          if (bOrderIndex === undefined) return -1
          if (aOrderIndex !== bOrderIndex) return aOrderIndex - bOrderIndex
        }
        if (a.latestTimestamp !== b.latestTimestamp) return b.latestTimestamp - a.latestTimestamp
        return getDirectorySortName(a).localeCompare(getDirectorySortName(b))
      })

    // Legacy, unbound, or hidden-project sessions remain discoverable without
    // becoming synthetic cwd roots or taking precedence over normal projects.
    return [...projectGroups, ...fallbackGroups]
  }

  const projectConversationGroups = computed(() => buildProjectConversationGroups(normalProjectConversations.value))
  const allProjectConversationGroups = computed(() => {
    return buildProjectConversationGroups(conversations.value.filter(conv => !isExternalImConversation(conv)))
  })

  const setProjectExpanded = (projectKey, expanded) => {
    if (!projectKey) return
    const current = new Set(expandedProjectKeys.value)
    if (expanded) {
      current.add(projectKey)
    } else {
      current.delete(projectKey)
    }
    expandedProjectKeys.value = Array.from(current)
    saveStringList(EXPANDED_PROJECTS_STORAGE_KEY, expandedProjectKeys.value)
  }

  const toggleProjectExpanded = (projectKey) => {
    setProjectExpanded(projectKey, !expandedProjectKeys.value.includes(projectKey))
  }

  const expandProject = (projectKey) => {
    setProjectExpanded(projectKey, true)
  }

  const toggleExternalImExpanded = () => {
    setProjectExpanded(EXTERNAL_IM_GROUP_KEY, !externalImExpanded.value)
  }

  const expandExternalImGroup = () => {
    setProjectExpanded(EXTERNAL_IM_GROUP_KEY, true)
  }

  const collapseOtherProjects = (projectKey) => {
    if (!projectKey) return
    expandedProjectKeys.value = [projectKey]
    saveStringList(EXPANDED_PROJECTS_STORAGE_KEY, expandedProjectKeys.value)
  }

  const moveProject = (projectKey, targetProjectKey, placement = 'before') => {
    if (!projectKey || !targetProjectKey || projectKey === targetProjectKey) return

    const groups = allProjectConversationGroups.value
    const project = groups.find(group => group.key === projectKey)
    const target = groups.find(group => group.key === targetProjectKey)
    if (!project || !target || project.isFallback || target.isFallback || project.pinned !== target.pinned) return

    const segmentGroups = groups.filter(group => group.pinned === project.pinned)
    const currentKeys = segmentGroups.map(group => group.key)
    const nextKeys = currentKeys.filter(key => key !== projectKey)
    const targetIndex = nextKeys.indexOf(targetProjectKey)
    if (targetIndex === -1) return

    nextKeys.splice(targetIndex + (placement === 'after' ? 1 : 0), 0, projectKey)

    if (project.pinned) {
      const knownKeys = new Set(currentKeys)
      const retainedKeys = pinnedProjectKeys.value.filter(key => !knownKeys.has(key))
      pinnedProjectKeys.value = [...nextKeys, ...retainedKeys]
      saveStringList(PINNED_PROJECTS_STORAGE_KEY, pinnedProjectKeys.value)
      return
    }

    const knownKeys = new Set(currentKeys)
    const retainedKeys = projectOrderKeys.value.filter(key => !knownKeys.has(key))
    projectOrderKeys.value = [...retainedKeys, ...nextKeys]
    saveStringList(PROJECT_ORDER_STORAGE_KEY, projectOrderKeys.value)
  }

  const toggleProjectPinned = (projectKey) => {
    const project = allProjectConversationGroups.value.find(group => group.key === projectKey)
    if (!project || project.isFallback) return
    const current = pinnedProjectKeys.value.filter(key => key !== projectKey)
    pinnedProjectKeys.value = isProjectPinned(projectKey)
      ? current
      : [projectKey, ...current]
    projectOrderKeys.value = projectOrderKeys.value.filter(key => key !== projectKey)
    saveStringList(PINNED_PROJECTS_STORAGE_KEY, pinnedProjectKeys.value)
    saveStringList(PROJECT_ORDER_STORAGE_KEY, projectOrderKeys.value)
  }

  /**
   * 按时间分组（今天、昨天、更早）
   */
  const groupedConversations = computed(() => {
    const now = new Date()
    const today = new Date(now.getFullYear(), now.getMonth(), now.getDate())
    const yesterday = new Date(today.getTime() - 86400000)

    const groups = {
      today: [],
      yesterday: [],
      older: []
    }

    for (const conv of filteredConversations.value) {
      const ts = new Date(conv.updatedAt || conv.createdAt)
      if (ts >= today) {
        groups.today.push(conv)
      } else if (ts >= yesterday) {
        groups.yesterday.push(conv)
      } else {
        groups.older.push(conv)
      }
    }

    return groups
  })

  return {
    conversations,
    loading,
    selectedCwd,
    selectedSource,
    selectedTaskFilter,
    selectedAppFilter,
    availableDirectories,
    appFilterOptions,
    pinnedProjectKeys,
    projectOrderKeys,
    expandedProjectKeys,
    selectCwd,
    projectConversationGroups,
    externalImConversations,
    externalImExpanded,
    toggleProjectPinned,
    moveProject,
    toggleProjectExpanded,
    expandProject,
    toggleExternalImExpanded,
    expandExternalImGroup,
    collapseOtherProjects,
    groupedConversations,
    loadConversations,
    createConversation,
    closeConversation,
    deleteConversation,
    bumpConversation,
    renameConversation
  }
}
